export const PSYCHOLOGISTS = [
  {
    id: 'nadia',
    name: 'Nadia Putri',
    credential: 'M.Psi., Psikolog',
    specialties: ['Kecemasan', 'Self-Love'],
    price: 180000,
    rating: 4.9,
    reviews: 128,
    years: 6,
    available: true,
    schedule: 'Hari ini · 13.00–17.00 WIB',
    quote: 'Kita mulai dari apa yang paling ingin kamu ceritakan.',
    initials: 'NP',
  },
  {
    id: 'reza',
    name: 'Reza Aditya',
    credential: 'M.Psi., Psikolog',
    specialties: ['Keluarga', 'Hubungan'],
    price: 200000,
    rating: 4.9,
    reviews: 96,
    years: 8,
    available: true,
    schedule: 'Hari ini · 15.00–20.00 WIB',
    quote: 'Setiap hubungan punya ruang untuk saling memahami.',
    initials: 'RA',
  },
  {
    id: 'ayu',
    name: 'Ayu Lestari',
    credential: 'M.Psi., Psikolog',
    specialties: ['Kecemasan', 'Burnout'],
    price: 175000,
    rating: 4.8,
    reviews: 84,
    years: 5,
    available: false,
    schedule: 'Jadwal berikutnya belum dibuka',
    quote: 'Kamu boleh beristirahat, tanpa merasa bersalah.',
    initials: 'AL',
  },
  {
    id: 'dimas',
    name: 'Dimas Pratama',
    credential: 'M.Psi., Psikolog',
    specialties: ['Self-Love', 'Burnout'],
    price: 160000,
    rating: 4.8,
    reviews: 72,
    years: 4,
    available: true,
    schedule: 'Hari ini · 16.00–21.00 WIB',
    quote: 'Mengenal diri adalah perjalanan, bukan perlombaan.',
    initials: 'DP',
  },
  {
    id: 'sari',
    name: 'Sari Wulandari',
    credential: 'M.Psi., Psikolog',
    specialties: ['Keluarga', 'Pengasuhan'],
    price: 225000,
    rating: 5.0,
    reviews: 110,
    years: 10,
    available: false,
    schedule: 'Jadwal berikutnya belum dibuka',
    quote: 'Orang tua juga butuh ruang untuk didengarkan.',
    initials: 'SW',
  },
  {
    id: 'farhan',
    name: 'Farhan Ramadhan',
    credential: 'M.Psi., Psikolog',
    specialties: ['Kecemasan', 'Hubungan'],
    price: 190000,
    rating: 4.9,
    reviews: 89,
    years: 7,
    available: true,
    schedule: 'Hari ini · 18.00–22.00 WIB',
    quote: 'Tidak perlu menyiapkan kata-kata yang sempurna.',
    initials: 'FR',
  },
] as const;
export type Doctor = (typeof PSYCHOLOGISTS)[number];
export const TOPICS = ['Semua', 'Kecemasan', 'Keluarga', 'Self-Love'] as const;
export type Topic = (typeof TOPICS)[number];
export const ARTICLES = [
  {
    id: 'grounding',
    category: 'Kecemasan',
    type: 'article',
    duration: '2 menit baca',
    title: 'Saat pikiran terasa penuh, kembali ke saat ini.',
    subtitle:
      'Mengenal grounding, satu latihan kecil untuk memberi ruang pada dirimu.',
    symbol: 'wind',
    paragraphs: [
      'Ketika perhatian terseret kekhawatiran, kamu bisa mencoba kembali menyadari hal-hal yang ada di sekitarmu. Ini adalah latihan perhatian, bukan cara untuk memaksa perasaan segera hilang.',
      'Rasakan telapak kaki menyentuh lantai. Perhatikan beberapa benda yang kamu lihat dan suara yang kamu dengar. Gerakkan tangan perlahan, lalu arahkan kembali perhatian ke satu kegiatan sederhana di depanmu.',
      'Cobalah sebentar sesuai kenyamananmu. Jika latihan terasa tidak nyaman, kamu boleh berhenti. Bila kesulitan terus mengganggu kegiatan sehari-hari, pertimbangkan dukungan tenaga profesional.',
    ],
    source: 'Panduan pengelolaan stres WHO',
    sourceUrl:
      'https://www.who.int/thailand/activities/doing-what-matters-in-times-of-stress',
  },
  {
    id: 'listening',
    category: 'Keluarga',
    type: 'article',
    duration: '2 menit baca',
    title: 'Mendengar dulu, memberi nasihat kemudian.',
    subtitle:
      'Percakapan kecil yang membuka ruang aman antara orang tua dan anak.',
    symbol: 'family',
    paragraphs: [
      'Ada cerita yang hanya membutuhkan pendengar. Sebelum menyampaikan pendapat, coba tanyakan: “Kamu ingin didengarkan, atau ingin mencari jalan keluar bersama?”',
      'Sediakan waktu tanpa distraksi. Beri jeda ketika orang yang kamu sayangi sedang memilih kata. Kamu dapat mengulang apa yang kamu tangkap, lalu memberi mereka kesempatan untuk meluruskan.',
      'Kamu tidak harus langsung menyelesaikan semuanya. Percakapan dapat dilanjutkan ketika semua pihak merasa siap. Batas yang saling disepakati tetap penting, termasuk hak untuk beristirahat dari pembicaraan.',
    ],
    source: 'Refleksi editorial Catharsa',
    sourceUrl: '',
  },
  {
    id: 'kindness',
    category: 'Self-Love',
    type: 'article',
    duration: '2 menit baca',
    title: 'Kamu tidak perlu selalu produktif.',
    subtitle:
      'Memberi diri sendiri izin beristirahat, tanpa perlu membuktikan apa pun.',
    symbol: 'heart',
    paragraphs: [
      'Daftar pekerjaan bukan satu-satunya cara melihat hari. Ada hari ketika merawat diri berarti menyelesaikan sesuatu. Ada pula hari ketika berhenti sejenak adalah pilihan yang kamu butuhkan.',
      'Coba tuliskan satu hal yang sudah kamu usahakan, meski kecil. Lalu tanyakan: “Apa yang akan kukatakan kepada seorang teman yang sedang mengalami hal yang sama?”',
      'Pilih satu bentuk istirahat yang terasa masuk akal untukmu. Tidak harus sempurna atau lama. Catatan ini adalah ajakan refleksi; kamu boleh memilih cara lain yang lebih sesuai.',
    ],
    source: 'Refleksi editorial Catharsa',
    sourceUrl: '',
  },
  {
    id: 'who-video',
    category: 'Kecemasan',
    type: 'video',
    duration: '2:12 · Video WHO',
    title: 'Langkah kecil menghadapi stres.',
    subtitle:
      'Pengantar panduan Doing What Matters dari WHO. Video berbahasa Inggris.',
    symbol: 'video',
    videoId: 'E3Cts45FNrk',
    paragraphs: [
      'Video resmi World Health Organization ini memperkenalkan panduan praktis untuk menghadapi stres. Aktifkan subtitle melalui pengaturan pemutar jika tersedia.',
    ],
    source: 'World Health Organization',
    sourceUrl: 'https://www.youtube.com/watch?v=E3Cts45FNrk',
  },
  {
    id: 'boundaries',
    category: 'Keluarga',
    type: 'article',
    duration: '2 menit baca',
    title: 'Batas yang sehat juga bentuk kasih sayang.',
    subtitle: 'Belajar menyampaikan kebutuhanmu dengan kalimat yang sederhana.',
    symbol: 'family',
    paragraphs: [
      'Kedekatan tidak selalu berarti tersedia setiap saat. Kamu bisa menyayangi seseorang sekaligus membutuhkan waktu untuk diri sendiri.',
      'Mulai dari satu kebutuhan yang spesifik: “Aku ingin mendengarkan, tetapi aku perlu istirahat dulu. Bisakah kita melanjutkan besok?” Gunakan kalimat yang menggambarkan kebutuhanmu tanpa menebak niat orang lain.',
      'Respons orang lain tidak selalu sesuai harapan. Kamu boleh mengulangi kebutuhanmu dengan tenang dan menyesuaikan batas yang realistis. Untuk situasi yang membuatmu tidak aman, mintalah dukungan orang tepercaya.',
    ],
    source: 'Refleksi editorial Catharsa',
    sourceUrl: '',
  },
  {
    id: 'mindful',
    category: 'Self-Love',
    type: 'article',
    duration: '2 menit baca',
    title: 'Hadir sebentar, bersama dirimu sendiri.',
    subtitle:
      'Mencoba perhatian penuh lewat hal-hal yang sudah ada dalam harimu.',
    symbol: 'leaf',
    paragraphs: [
      'Perhatian penuh dapat dimulai dengan menyadari pengalaman saat ini. Misalnya, perhatikan rasa dan aroma minuman atau suara di sekitar saat berjalan.',
      'Ketika pikiran berkelana, sadari dengan lembut lalu kembalikan perhatian. Tujuannya bukan mengosongkan pikiran atau menilai dirimu berhasil atau gagal.',
      'Pendekatan ini tidak cocok untuk semua orang. Jika membuatmu semakin tidak nyaman, berhenti dan pilih kegiatan lain. Kamu dapat membicarakan pengalamanmu dengan tenaga profesional bila perlu.',
    ],
    source: 'NHS — Mindfulness',
    sourceUrl:
      'https://www.nhs.uk/mental-health/self-help/tips-and-support/mindfulness/',
  },
] as const;
export type Article = (typeof ARTICLES)[number];
export const MOOD_SAMPLES = [3, 4, 2, 3, 4, 3, 4];
